syntax on "構文を色分け表示
set number "行番号
set expandtab "インデントをスペースにする
set tabstop=2 "tabスペースを2
set shiftwidth=2 "vimでfileを読み込む時にtabを2スペースに変換
set smartindent "改行時に自動インデント
set backspace=indent,eol,start "backspaceを行の初め，終わりで使えるようになる
set nobackup "バックアップファイルを作らないようにする
set noswapfile "swapファイルを作らないようにする
set autoread "開いているときに他から変更されたら自動で読み込んでくれる
set hidden "保存されていないファイルがあるときでも別のファイルを開ける
set showcmd "入力中のコマンドを表示する
set virtualedit=onemore "カーソルを行末のもう一つ先まで動かせる
set wrapscan "最後まで検索したら最初に戻る
set hlsearch "検索している文字列に色をつける
set mouse=a "クリック有効化
set nowrap "1行が長い時に折り返して表示させない
set ignorecase "検索時に大文字、小文字を区別しない
set smartcase "検索パターンが大文字を含んでいたらignorecaseを上書きする
set incsearch "検索途中でマッチする箇所に移動する
set laststatus=2 "最下ウィンドウにステータス行を常に表示
set ruler "ルーラ設定
set cursorline "カーソルのある行の色を変える
